### ISSUE TITLE
Rails 6 and rc1, uninitialized constant ActionDispatch::Routing::ACTIVE_SCAFFOLD_CORE_ROUTING (NameError)

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold_export#1]
I wanted to try this gem.  My Rails application has the following gem versions:

```
gem 'active_scaffold', '~> 3.6.0.rc1'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'active_scaffold_export'
gem 'axlsx_rails'
gem 'rails', '~> 6.0'
gem 'mysql2'
```

When I try to start the server, I get 

```
Traceback (most recent call last):
	33: from bin/rails:3:in `<main>'
	32: from bin/rails:3:in `load'
	31: from /Users/dbulgatz/AMA/t3-mis/bin/spring:15:in `<top (required)>'
	30: from /Users/dbulgatz/AMA/t3-mis/bin/spring:15:in `require'
	29: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	28: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	27: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	26: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	25: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	24: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	23: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	22: from /Users/dbulgatz/AMA/t3-mis/bin/rails:9:in `<top (required)>'
	21: from /Users/dbulgatz/AMA/t3-mis/bin/rails:9:in `require'
	20: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<top (required)>'
	19: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
	18: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
	17: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	16: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	14: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	13: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	12: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	11: from /Users/dbulgatz/AMA/t3-mis/config/application.rb:8:in `<top (required)>'
	10: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	 9: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	 8: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	 7: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	 6: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	 5: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	 4: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
	 3: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_scaffold_export-3.3.2/lib/active_scaffold_export.rb:8:in `<top (required)>'
	 2: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_scaffold_export-3.3.2/lib/active_scaffold_export/config/core.rb:2:in `<top (required)>'
	 1: from /Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_scaffold_export-3.3.2/lib/active_scaffold_export/config/core.rb:2:in `class_eval'
/Users/dbulgatz/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/active_scaffold_export-3.3.2/lib/active_scaffold_export/config/core.rb:18:in `block in <top (required)>': uninitialized constant ActionDispatch::Routing::ACTIVE_SCAFFOLD_CORE_ROUTING (NameError)
```

**Comment by scambra** [comment]
Fixed in master branch
